### ISSUE TITLE
Suggestion for different setup

### ISSUE THREAD

**Issue by ewels** [drejom/rnaseq-ref#1]
Hi @drejom,

Great to see that you're finding our NGI-RNAseq pipeline useful! I found this repo after poking around to see who had forked / followed our repositories. This is exactly why we develop them on GitHub - open collaborative bioinformatics is the way to go :)

Anyway, after being nosy I have a couple of suggestions. It looks like most of the files come from our [SciLifeLab/NGI-RNAseq](https://github.com/SciLifeLab/NGI-RNAseq) repo, a little while back. We're still actively developing this pipeline and testing / fixing bugs. However, because of the way that you've set up this repository, it's kind of difficult for you to pull in any of our changes and I can see from your commits that you're fixing some things that we also fixed a few weeks back.

My suggestion (and it is purely that, a suggestion!) is that you could set this up in a slightly different way. Instead of replacing our config file, you can just tell NextFlow to load your own after ours using the `-c` parameter. You also have your own script to launch the pipeline. If it were me, I'd create a repository with these two files and then have [SciLifeLab/NGI-RNAseq](https://github.com/SciLifeLab/NGI-RNAseq) set up as a [git submodule](https://github.com/blog/2104-working-with-submodules). The launch script could call your custom config file (`nextflow run NGI-RNAseq/main.nf -c unsw.config` or similar).

By including our pipeline like this instead of copying the files, it makes it super easy to pull in our updates as we improve the pipeline - eg. `git submodule foreach git pull`. It does mean that you couldn't make changes to our files though - if you need that then forking the repository would be better.

Sorry for intruding anyway, I just thought that these suggestions could help you to avoid doing lots of bugfixing that we've already done for you!

Cheers,

Phil

**Comment by ewels** [comment]
Hello! I got a ping from the activity on this issue just now.. Note for any future Googlers that this comment is now well out of date. This pipeline is now part of https://nf-co.re and has lots of cool methods for local integration (and other stuff).

**Comment by drejom** [comment]
Thanks Phil! 
Was doing some tidying up and missed this. I’ll close this issue and repo - the nf-core work is brilliant. ive started working on a pipeline for SELEX aptamers that I hope to contribute soon.

**Comment by drejom** [comment]
Thanks Phil! 
Was doing some tidying up and missed this. I’ll close this issue and repo - the nf-core work is brilliant. ive started working on a pipeline for SELEX aptamers that I hope to contribute soon.

**Comment by ewels** [comment]
Sounds great!
